'use strict';
window.app = window.app || {};
window.app.repository = window.app.repository || {};

(function(repository) {
    var FoodsRepository = function() {
        this.foods = [
            {"name": "Stopfleber***", "gi": "0"},
            {"name": "Alkohol", "gi": "0"},
            {"name": "Fisch (Lachs, Thunfisch, Sardinen, Sardellen, etc.)***", "gi": "0"},
            {"name": "Käse (Mozzarella, Camembert, Emmentaler, etc.)***", "gi": "0"},
            {"name": "Fleisch***", "gi": "0"},
            {"name": "Rotwein, Weißwein, Champagner***", "gi": "0"},
            {"name": "Wurst (Salami, Würstchen, etc.), Schinken***", "gi": "0"},
            {"name": "Meeresfrüchte*** (Garnelen, Muscheln, Austern)", "gi": "0"},
            {"name": "Mayonnaise (selbst gemacht: Eier, Öl, Senf)", "gi": "0"},
            {"name": "Gänsefett, Margarine***", "gi": "0"},
            {"name": "Eier***", "gi": "0"},
            {"name": "Kaffee, Tee***", "gi": "0"},
            {"name": "Geflügel*** (Hähnchen, Pute, etc.)", "gi": "0"},
            {"name": "Rind (Steak, Filet)***", "gi": "0"},
            {"name": "Sauerrahm, Crème fraîche***/**", "gi": "0"},
            {"name": "Sojasauce ohne Zucker und Farbstoffe", "gi": "0"},
            {"name": "Öl (Olivenöl, Sonnenblumenöl, etc.)***", "gi": "0"},
            {"name": "Krustentiere (Hummer, Krabben, Languste)", "gi": "5"},
            {"name": "Gewürze, Kräuter (Pfeffer, Petersilie, Basilikum, Oregano, Zimt, Vanille, etc.)", "gi": "5"},
            {"name": "Essig", "gi": "5"},
            {"name": "Balsamico Essig", "gi": "5"},
            {"name": "Avocado", "gi": "10"},
            {"name": "Spaghetti, mit niedrigem GI (Montignac®)", "gi": "14"},
            {"name": "Nudeln, Spaghetti, mit niedrigem GI (Montignac®)", "gi": "14"},
            {"name": "Mangold", "gi": "15"},
            {"name": "Lupine (Süßlupine)", "gi": "15"},
            {"name": "Kleie (Weizen, Hafer ...)", "gi": "15"},
            {"name": "Agavensirup", "gi": "15"},
            {"name": "Spargel", "gi": "15"},
            {"name": "Gurke", "gi": "15"},
            {"name": "Brokkoli", "gi": "15"},
            {"name": "Oliven", "gi": "15"},
            {"name": "Mandeln", "gi": "15"},
            {"name": "Zwiebeln", "gi": "15"},
            {"name": "Champignons, Pilze", "gi": "15"},
            {"name": "Soja", "gi": "15"},
            {"name": "Tofu", "gi": "15"},
            {"name": "Ingwer", "gi": "15"},
            {"name": "Radieschen, Rettich", "gi": "15"},
            {"name": "Rosenkohl", "gi": "15"},
            {"name": "Chicoree", "gi": "15"},
            {"name": "Pesto", "gi": "15"},
            {"name": "Pinienkerne", "gi": "15"},
            {"name": "Rhabarber", "gi": "15"},
            {"name": "Fenchel", "gi": "15"},
            {"name": "Stangensellerie", "gi": "15"},
            {"name": "Pepperoni", "gi": "15"},
            {"name": "Pistazien", "gi": "15"},
            {"name": "Paprika", "gi": "15"},
            {"name": "Sauerkraut", "gi": "15"},
            {"name": "Schalotte", "gi": "15"},
            {"name": "Johannisbeeren, schwarz", "gi": "15"},
            {"name": "Essiggurken", "gi": "15"},
            {"name": "Johannisbrotmehl (Carobpulver)", "gi": "15"},
            {"name": "Spinat", "gi": "15"},
            {"name": "Zucchini", "gi": "15"},
            {"name": "Lauch, Frühlingszwiebel", "gi": "15"},
            {"name": "Nüsse", "gi": "15"},
            {"name": "Salat, grün", "gi": "15"},
            {"name": "Kohl, Kraut", "gi": "15"},
            {"name": "Erdnüsse", "gi": "15"},
            {"name": "Sauerampfer", "gi": "15"},
            {"name": "Sprossen", "gi": "15"},
            {"name": "Physalis, Kapstachelbeere", "gi": "15"},
            {"name": "Getreide, gekeimt", "gi": "15"},
            {"name": "Blumenkohl", "gi": "15"},
            {"name": "Tempeh", "gi": "15"},
            {"name": "Stangenbohnen", "gi": "15"},
            {"name": "Zuckererbsenschote", "gi": "15"},
            {"name": "Weizenkeime", "gi": "15"},
            {"name": "Ratatouille", "gi": "20"},
            {"name": "Zitronensaft, ohne Zucker", "gi": "20"},
            {"name": "Kakaopulver, ohne Zucker", "gi": "20"},
            {"name": "Aubergine", "gi": "20"},
            {"name": "Sojajoghurt (natur)", "gi": "20"},
            {"name": "Bambussprossen", "gi": "20"},
            {"name": "Karotten, roh", "gi": "20"},
            {"name": "Schokolade, schwarz (über 85 % Kakaogehalt)", "gi": "20"},
            {"name": "Palmherzen", "gi": "20"},
            {"name": "Artischocke", "gi": "20"},
            {"name": "Acerolakirsche, Antillenkirsche", "gi": "20"},
            {"name": "Soja-Sahne", "gi": "20"},
            {"name": "Tamarisoße (ohne Zucker oder Süßstoff)", "gi": "20"},
            {"name": "Fruktose, Fruchtzucker (Montignac®)", "gi": "20"},
            {"name": "Zitrone", "gi": "20"},
            {"name": "Konfitüre, Marmelade, ohne Zucker (Montignac®)", "gi": "20"},
            {"name": "Mandeln, gemahlen", "gi": "20"},
            {"name": "Haselnuss, gemahlen", "gi": "20"},
            {"name": "Schokolade, schwarz (über 70 % Kakaogehalt)", "gi": "25"},
            {"name": "Erdnussmus, ungezuckert", "gi": "25"},
            {"name": "Himbeere, frisch", "gi": "25"},
            {"name": "Mandelmus, ungezuckert (aus ganzen Mandeln)", "gi": "25"},
            {"name": "Haselnuss", "gi": "25"},
            {"name": "Hummus (vegetarischer Brotaufstrich aus Kichererbsen)", "gi": "25"},
            {"name": "Cashewkerne", "gi": "25"},
            {"name": "Brombeeren", "gi": "25"},
            {"name": "Haselnussmus, ungezuckert", "gi": "25"},
            {"name": "Linsen, grün", "gi": "25"},
            {"name": "Heidelbeeren", "gi": "25"},
            {"name": "Stachelbeere", "gi": "25"},
            {"name": "Grapefruit, frisch", "gi": "25"},
            {"name": "Erdbeeren, frisch", "gi": "25"},
            {"name": "Kürbiskerne", "gi": "25"},
            {"name": "Kirschen", "gi": "25"},
            {"name": "Johannisbeeren, rot", "gi": "25"},
            {"name": "Sojamehl", "gi": "25"},
            {"name": "Mungobohnen", "gi": "25"},
            {"name": "Bohnenkerne, grün (Flageolet)", "gi": "25"},
            {"name": "Gerstengraupen, grob", "gi": "25"},
            {"name": "Spalterbsen", "gi": "25"},
            {"name": "Goji Beere", "gi": "25"},
            {"name": "pęczak", "gi": "25"},
            {"name": "Mandarinen, Clementinen", "gi": "30"},
            {"name": "Weiße Bohnen, Perlbohnen", "gi": "30"},
            {"name": "Tomate", "gi": "30"},
            {"name": "Knoblauch", "gi": "30"},
            {"name": "Marmelade, ohne Zucker", "gi": "30"},
            {"name": "Bohnen, grün", "gi": "30"},
            {"name": "Sojamilch", "gi": "30"},
            {"name": "Apfel, getrocknet", "gi": "30"},
            {"name": "Linsen, braun", "gi": "30"},
            {"name": "Rote Bete, roh", "gi": "30"},
            {"name": "Passionsfrucht, Maracuja, Grenadille", "gi": "30"},
            {"name": "Mandelmilch", "gi": "30"},
            {"name": "Quark, nicht abgetropft**", "gi": "30"},
            {"name": "Milch aus Milchpulver**", "gi": "30"},
            {"name": "Sojanudeln", "gi": "30"},
            {"name": "Milch (vollfett oder fettarm)**", "gi": "30"},
            {"name": "Weiße Rübe, roh", "gi": "30"},
            {"name": "Linsen, gelb", "gi": "30"},
            {"name": "Schwarzwurzeln", "gi": "30"},
            {"name": "Birne, frisch", "gi": "30"},
            {"name": "Hafermilch (ungekocht)", "gi": "30"},
            {"name": "Gerstengraupen, fein (Perlgraupen)", "gi": "30"},
            {"name": "Aprikosen, getrocknet", "gi": "30"},
            {"name": "Pumpernickel (Montignac®)", "gi": "32"},
            {"name": "Vollkornbrot (Montignac®)", "gi": "34"},
            {"name": "Sprossenbrot (aus gekeimtem Getreide)", "gi": "35"},
            {"name": "Granatapfel, frisch", "gi": "35"},
            {"name": "Banane, leicht grün", "gi": "35"},
            {"name": "Amarant", "gi": "35"},
            {"name": "Joghurt**", "gi": "35"},
            {"name": "Tomaten, getrocknet", "gi": "35"},
            {"name": "Pflaume, frisch", "gi": "35"},
            {"name": "Quinoa", "gi": "35"},
            {"name": "Tomatensaft", "gi": "35"},
            {"name": "Kichererbsen", "gi": "35"},
            {"name": "Aprikosen, frisch", "gi": "35"},
            {"name": "Apfelmus, Apfelkompott", "gi": "35"},
            {"name": "Hefe", "gi": "35"},
            {"name": "Orange, frisch", "gi": "35"},
            {"name": "Mandelmus, ungezuckert (aus geschälten Mandeln)", "gi": "35"},
            {"name": "Senf, scharf", "gi": "35"},
            {"name": "Bohnen, schwarz", "gi": "35"},
            {"name": "Apfel, frisch", "gi": "35"},
            {"name": "Bohnen, rot", "gi": "35"},
            {"name": "Adzuki-Bohnen", "gi": "35"},
            {"name": "Suppennudeln aus Hartweizen", "gi": "35"},
            {"name": "Sonnenblumenkerne", "gi": "35"},
            {"name": "Bierhefe", "gi": "35"},
            {"name": "Feige, frisch", "gi": "35"},
            {"name": "Wasa Köstlich (24 % Ballaststoffgehalt)", "gi": "35"},
            {"name": "Tomatensoße, ohne Zucker", "gi": "35"},
            {"name": "Falafel (aus Kichererbsen)", "gi": "35"},
            {"name": "Eiscreme (mit Fruchtzucker)", "gi": "35"},
            {"name": "Wildreis", "gi": "35"},
            {"name": "Nektarine", "gi": "35"},
            {"name": "Leinsamen/Sesam/Mohn, ganz", "gi": "35"},
            {"name": "Kichererbsenmehl", "gi": "35"},
            {"name": "Cherimoya, Zimtapfel, Annonenfrucht", "gi": "35"},
            {"name": "Cassoulet (franz. Bohnen-Fleisch-Eintopf)", "gi": "35"},
            {"name": "Bohnen, Borlotti", "gi": "35"},
            {"name": "Kichererbsen (Dose)", "gi": "35"},
            {"name": "Pfirsich, frisch", "gi": "35"},
            {"name": "Sellerie, roh", "gi": "35"},
            {"name": "Quitte, frisch", "gi": "35"},
            {"name": "Erbsen, frisch", "gi": "35"},
            {"name": "Schokoladenriegel, ohne Zucker (Montignac®)", "gi": "35"},
            {"name": "Mais, ursprünglicher (Indien)", "gi": "35"},
            {"name": "Erbsen, frisch", "gi": "35"},
            {"name": "Kokosnuss", "gi": "35"},
            {"name": "Kokosnuss, gemahlen", "gi": "35"},
            {"name": "Emmer (alte Getreidesorte)", "gi": "40"},
            {"name": "Quittengelee (ohne Zucker)", "gi": "40"},
            {"name": "Pepino, Melonenbirne", "gi": "40"},
            {"name": "Jamswurzel", "gi": "40"},
            {"name": "Ravioli (aus Hartweizen)", "gi": "40"},
            {"name": "Apfelsaft, ungezuckert", "gi": "40"},
            {"name": "Karottensaft, ohne Zucker", "gi": "40"},
            {"name": "Sesammus, Tahin", "gi": "40"},
            {"name": "Dicke Bohnen, roh", "gi": "40"},
            {"name": "Pflaumen, getrocknet", "gi": "40"},
            {"name": "Hafer", "gi": "40"},
            {"name": "Kokosmilch", "gi": "40"},
            {"name": "Karotten, gekocht*", "gi": "40"},
            {"name": "Apfelwein, trocken", "gi": "40"},
            {"name": "Vollkornnudeln, al dente", "gi": "40"},
            {"name": "Kamut, Vollkorn", "gi": "40"},
            {"name": "Bohnen, rot (Dose)", "gi": "40"},
            {"name": "Vollkornbrot (100 %) mit Hefe/Sauerteig", "gi": "40"},
            {"name": "Matzen (ungesäuertes Fladenbrot, Vollkornmehl)", "gi": "40"},
            {"name": "Sorbet, ohne Zucker", "gi": "40"},
            {"name": "Sandgebäck aus Vollkornmehl, ohne Zucker", "gi": "40"},
            {"name": "Erdnussbutter", "gi": "40"},
            {"name": "Zichorie (Getränk)", "gi": "40"},
            {"name": "Haferflocken, grob", "gi": "40"},
            {"name": "Falafel (aus Bohnen)", "gi": "40"},
            {"name": "Quinoamehl", "gi": "40"},
            {"name": "Buchweizen Pfannkuchen", "gi": "40"},
            {"name": "Buchweizen Pasta", "gi": "40"},
            {"name": "Spaghetti, Vollkorn, al dente gekocht", "gi": "40"},
            {"name": "Hartweizen, trocken, vorgegart (10 Min. Kochzeit)", "gi": "45"},
            {"name": "Emmer-Vollkornmehl (alte Getreidesorte)", "gi": "45"},
            {"name": "Blé, pilpil de", "gi": "45"},
            {"name": "Mangosaft, ohne Zucker", "gi": "45"},
            {"name": "Traubensaft (ungezuckert)", "gi": "45"},
            {"name": "Capellini (dünne Spaghetti)", "gi": "45"},
            {"name": "Grapefruitsaft, ungezuckert", "gi": "45"},
            {"name": "Orangensaft, zuckerfrei", "gi": "45"},
            {"name": "Banane, jaune (sans taches noires)", "gi": "45"},
            {"name": "Kochbanane, roh", "gi": "45"},
            {"name": "Couscous, Vollkorn", "gi": "45"},
            {"name": "Tomatensoße (mit Zucker)", "gi": "45"},
            {"name": "Trauben, frisch", "gi": "45"},
            {"name": "Milchzucker", "gi": "45"},
            {"name": "Kamutbrot", "gi": "45"},
            {"name": "Kamut-Vollkornmehl", "gi": "45"},
            {"name": "Vollkorntoast, ohne Zucker", "gi": "45"},
            {"name": "Erbsen (Dose)", "gi": "45"},
            {"name": "Vollkornbulgur (gekocht)", "gi": "45"},
            {"name": "Preiselbeeren", "gi": "45"},
            {"name": "Vollkorncerealien, ohne Zucker", "gi": "45"},
            {"name": "Dinkel (Vollkorn)", "gi": "45"},
            {"name": "Dinkel (Vollkorn)", "gi": "45"},
            {"name": "Fruchtaufstrich (Konfitüre), ohne Zucker", "gi": "45"},
            {"name": "Müsli (Montignac®)", "gi": "45"},
            {"name": "Pumpernickel", "gi": "45"},
            {"name": "Spaghetti, al dente gekocht (5 Minuten)", "gi": "45"},
            {"name": "Basmatireis, Vollkorn", "gi": "45"},
            {"name": "Weizenvollkornmehl", "gi": "45"},
            {"name": "Banane, grün", "gi": "45"},
            {"name": "Marmelade, gezuckert", "gi": "50"},
            {"name": "Tamarinde, süß", "gi": "50"},
            {"name": "Ananas (Dose)", "gi": "50"},
            {"name": "Pfirsich (Dose, gezuckert)", "gi": "50"},
            {"name": "Ananassaft, ungezuckert", "gi": "50"},
            {"name": "Basmatireis, Langkorn", "gi": "50"},
            {"name": "Mango", "gi": "50"},
            {"name": "Bulgur (gekocht )", "gi": "50"},
            {"name": "Sushi", "gi": "50"},
            {"name": "Surimi", "gi": "50"},
            {"name": "Topinambur, Erdbirne", "gi": "50"},
            {"name": "Müsli, ohne Zucker", "gi": "50"},
            {"name": "Kaki", "gi": "50"},
            {"name": "Kiwi*", "gi": "50"},
            {"name": "Süßkartoffeln", "gi": "50"},
            {"name": "All Bran™ von Kelloggs", "gi": "50"},
            {"name": "Wasa™ light rye", "gi": "50"},
            {"name": "Energieriegel, ungezuckert", "gi": "50"},
            {"name": "Litschi/Lychee, frisch", "gi": "50"},
            {"name": "Naturreis", "gi": "50"},
            {"name": "Vollkornnudeln", "gi": "50"},
            {"name": "Feigen, getrocknet", "gi": "50"},
            {"name": "Ananas (frische Frucht)", "gi": "50"},
            {"name": "Brot mit Quinoa (ca. 65 % Quinoa)", "gi": "50"},
            {"name": "Buchweizen, Vollkorn (dunkles Korn)", "gi": "50"},
            {"name": "Sojajoghurt (aromatisiert)", "gi": "50"},
            {"name": "Roggenvollkornbrot (100 %)", "gi": "50"},
            {"name": "Chayote, püriert", "gi": "50"},
            {"name": "Preiselbeer/Heidelbeersaft, ungezuckert", "gi": "50"},
            {"name": "Kekse aus Vollkornmehl, ohne Zucker", "gi": "50"},
            {"name": "Konfitüre, gezuckert", "gi": "50"},
            {"name": "Couscous (Vollkorngries)", "gi": "50"},
            {"name": "Makkaroni (aus Hartweizen)", "gi": "50"},
            {"name": "Banane, jaune (taches noires)", "gi": "50"},
            {"name": "Fonio", "gi": "50"},

            {"name": "Zuckermais", "gi": "55"},
            {"name": "Ahornsirup", "gi": "55"},
            {"name": "Pizza", "gi": "55"},
            {"name": "Banane, reif", "gi": "55"},
            {"name": "Senf, süß", "gi": "55"},
            {"name": "Ketchup", "gi": "55"},
            {"name": "Mispel", "gi": "55"},
            {"name": "Sandgebäck (Mehl, Butter, Zucker)", "gi": "55"},
            {"name": "Reis, rot", "gi": "55"},
            {"name": "Tagliatelle, weich gekocht", "gi": "55"},
            {"name": "Chicorée-Sirup", "gi": "55"},
            {"name": "Maniok, bitter", "gi": "55"},
            {"name": "Maniok, süß", "gi": "55"},
            {"name": "Datteln", "gi": "55"},
            {"name": "Spaghetti, weiß, weich gekocht", "gi": "55"},
            {"name": "Birnen, Konserve", "gi": "55"},
            {"name": "Reis, gepufft", "gi": "60"},
            {"name": "Special K®", "gi": "60"},
            {"name": "Chips", "gi": "60"},
            {"name": "Cola, Limonaden, Erfrischungsgetränke", "gi": "60"},
            {"name": "Croissant", "gi": "60"},
            {"name": "Couscous", "gi": "60"},
            {"name": "Milchbrot", "gi": "60"},
            {"name": "Porridge, gekocht aus Haferflocken", "gi": "60"},
            {"name": "Grieß (aus Hartweizen)", "gi": "60"},
            {"name": "Reis, Langkorn", "gi": "60"},
            {"name": "Eiscreme, gezuckert", "gi": "60"},
            {"name": "Ovomaltine", "gi": "60"},
            {"name": "Maronen, Esskastanien", "gi": "60"},
            {"name": "Lasagne (aus Hartweizen)", "gi": "60"},
            {"name": "Schokoladenpulver, gezuckert", "gi": "60"},
            {"name": "Reis aus der Camargue", "gi": "60"},
            {"name": "Honig", "gi": "60"},
            {"name": "Chinesische Reisnudeln", "gi": "60"},
            {"name": "Mars®, Snickers®, Nuts®, etc.", "gi": "60"},
            {"name": "Vollkornmehl", "gi": "60"},
            {"name": "Mayonnaise (industriell hergestellt, gezuckert)", "gi": "60"},
            {"name": "Fruchtcocktail in Zuckersirup, Konserve", "gi": "60"},
            {"name": "Papaya*", "gi": "60"},
            {"name": "Kürbis (verschiedene)*", "gi": "65"},
            {"name": "Kartoffeln mit Schale gegart (Wasser, Dampf)", "gi": "65"},
            {"name": "Mehrkornbrot", "gi": "65"},
            {"name": "Graubrot (mit Hefe)", "gi": "65"},
            {"name": "Rote Bete, gekocht*", "gi": "65"},
            {"name": "Rosinen", "gi": "65"},
            {"name": "Quittengelee (mit Zucker)", "gi": "65"},
            {"name": "Brotfrucht (Brotfruchtbaum)", "gi": "65"},
            {"name": "Sorbet, gezuckert", "gi": "65"},
            {"name": "Roggenbrot (30 % Roggen)", "gi": "65"},
            {"name": "Müsli (mit Zucker oder Honig gesüßt)", "gi": "65"},
            {"name": "Melone, Honigmelone*", "gi": "65"},
            {"name": "Schokobrötchen", "gi": "65"},
            {"name": "Getrockneter Zuckerrohrsaft", "gi": "65"},
            {"name": "Kastanienmehl", "gi": "65"},
            {"name": "Dinkel", "gi": "65"},
            {"name": "Aprikosen (Dose, mit Zucker)", "gi": "65"},
            {"name": "Dicke Bohnen, gekocht", "gi": "65"},
            {"name": "Mehl 50 % Vollkorn", "gi": "65"},
            {"name": "Nudeln aus Vollkornreismehl", "gi": "65"},
            {"name": "Kastanienmehl", "gi": "65"},
            {"name": "Rohrzucker", "gi": "65"},
            {"name": "Mais, gekocht", "gi": "65"},
            {"name": "Zucker, weiß (Saccharose)", "gi": "70"},
            {"name": "Popcorn (ohne Zucker)", "gi": "70"},
            {"name": "Maismehl", "gi": "70"},
            {"name": "Risotto", "gi": "70"},
            {"name": "Reis, weiß, Standard", "gi": "70"},
            {"name": "Tacos", "gi": "70"},
            {"name": "Schokoladenriegel, zuckerhaltig", "gi": "70"},
            {"name": "Gnocchi", "gi": "70"},
            {"name": "Teigwaren, Nudeln (aus Weichweizen)", "gi": "70"},
            {"name": "Melasse, Sirup", "gi": "70"},
            {"name": "Cerealien, raffiniert, gezuckert", "gi": "70"},
            {"name": "Maisbrei, Polenta", "gi": "70"},
            {"name": "Zwieback", "gi": "70"},
            {"name": "Bagels", "gi": "70"},
            {"name": "Biskuit", "gi": "70"},
            {"name": "Rohzucker", "gi": "70"},
            {"name": "Kochbanane (gekocht)", "gi": "70"},
            {"name": "Baguette, Weißbrot", "gi": "70"},
            {"name": "Reisbrot", "gi": "70"},
            {"name": "Brioche", "gi": "70"},
            {"name": "Salzkartoffeln", "gi": "70"},
            {"name": "Bier*", "gi": "70"},
            {"name": "Hirse", "gi": "70"},
            {"name": "Kohlrübe, Steckrübe (gekocht)", "gi": "70"},
            {"name": "Amarant, gepufft", "gi": "70"},
            {"name": "Ravioli (aus Weichweizen)", "gi": "70"},
            {"name": "Polenta, Maisgrieß", "gi": "70"},
            {"name": "Brot, ungesäuert (aus Weißmehl)", "gi": "70"},
            {"name": "Pellkartoffeln", "gi": "70"},
            {"name": "Jasminreis (Duftreis)", "gi": "70"},
            {"name": "Kohlrübe, gelbe, Steckrübe", "gi": "70"},
            {"name": "Wassermelone*", "gi": "75"},
            {"name": "Hamburgerbrötchen", "gi": "75"},
            {"name": "Lasagne (aus Weichweizen)", "gi": "75"},
            {"name": "Weißes Toastbrot", "gi": "75"},
            {"name": "Donuts, Berliner, Krapfen", "gi": "75"},
            {"name": "Schnellkochreis", "gi": "75"},
            {"name": "Waffeln (mit Zucker)", "gi": "75"},
            {"name": "Kürbis (Riesenkürbis)*", "gi": "75"},
            {"name": "Riz, farine de (complète)", "gi": "75"},
            {"name": "Sportgetränke", "gi": "75"},
            {"name": "Kartoffelpüree (selbst zubereitet)", "gi": "80"},
            {"name": "Crackers made from white flour", "gi": "80"},
            {"name": "Maizena", "gi": "85"},
            {"name": "Weißmehl", "gi": "85"},
            {"name": "Milchreis, gezuckert", "gi": "85"},
            {"name": "Reispudding, Reiskuchen", "gi": "85"},
            {"name": "Reismilch", "gi": "85"},
            {"name": "Weiße Rübe, gekocht*", "gi": "85"},
            {"name": "Sellerie (Knolle), gekocht*", "gi": "85"},
            {"name": "Tapioka", "gi": "85"},
            {"name": "Pastinake*", "gi": "85"},
            {"name": "Cornflakes, Maisflocken", "gi": "85"},
            {"name": "Pfeilwurzelmehl (Arrow Root)", "gi": "85"},
            {"name": "Weißbrot ohne Gluten", "gi": "90"},
            {"name": "Kartoffelpüree (Instantflocken)", "gi": "90"},
            {"name": "Klebreis, glutenhaltig", "gi": "90"},
            {"name": "Kartoffeln, gebacken mit Schale", "gi": "90"},
            {"name": "Reismehl", "gi": "95"},
            {"name": "Kartoffelstärke", "gi": "95"},
            {"name": "Kartoffelgratin, Bratkartoffeln", "gi": "95"},
            {"name": "Pommes frites", "gi": "95"},
            {"name": "Maltodextrin", "gi": "95"},
            {"name": "Maisstärke", "gi": "95"},
            {"name": "Reissirup", "gi": "95"},
            {"name": "Stärke, modifiziert", "gi": "100"},
            {"name": "Glukose (Traubenzucker)", "gi": "100"},
            {"name": "Glukosesirup", "gi": "100"},
            {"name": "Weizensirup, Reissirup", "gi": "100"},
            {"name": "Maissirup", "gi": "115"}
        ];
    };
    FoodsRepository.prototype.findAll = function() {
        return this.foods;
    };
    FoodsRepository.prototype.findByName = function() {
        return null;
    };

    repository.FoodsRepository = FoodsRepository;
})(window.app.repository);
